updated yml c:

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,12 +1,12 @@
 name: Weather Pipeline CI/CD (JS)
 
-on: 
+on:
   push:
   schedule:
     - cron: "0 */2 * * *"
   workflow_dispatch:
 permissions:
-    contents: write
+  contents: write
 jobs:
   test_and_fetch:
     runs-on: ubuntu-latest
@@ -25,17 +25,16 @@ jobs:
       - name: Install Dependencies
         run: npm CI
       - name: Fetch Latest Weather
-        env: 
+        env:
           WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
           WEATHER_CITY: ${{ secrets.WEATHER_CITY }}
           PORT: ${{ secrets.PORT }}
         run: nodefetchWeather.js
       - name: Commit weather data if changed
-        run: 
-            git config user.name "github-actions[bot]"
-            git config user.email "github-actions[bot]@users.noreply.github.com"
-            git add data/weather.json data/weather_log.csv || true
-            git commit -m "ci: update weather data" || echo "No changed to Commit"
-            git push || echo "Push failed or no changes"
+        run: git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add data/weather.json data/weather_log.csv || true
+          git commit -m "ci:update weather data" || echo "No changed to Commit"
+          git push || echo "Push failed or no changes"
       - name: Trigger Render Deploy
         run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
